spring:
  application:
    name: spirng-boot-rabbitmq
  rabbitmq:
    host: 47.100.241.49
    port: 5672
    username: admin
    password: 1z2x3c4v5b
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.241.49:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
